// ─────────────────────────────────────────────────────────────────────────────
// SKILL FORGE — ACTUAL Skill Creation (No Hallucination)
// Forces filesystem writes before claiming success
// ─────────────────────────────────────────────────────────────────────────────

import * as fs from "fs";
import * as path from "path";
import { app } from "electron";

const USER_SKILLS_PATH = path.join(app.getPath("userData"), "mosaicbot", "skills", "mosaicbot-authored");

export interface SkillTemplate {
  name: string;
  description: string;
  category: string;
  triggers: string[];
  content: string;
}

// ACTUALLY writes skill to disk — no hallucination possible
export function forgeSkill(skill: SkillTemplate): { success: boolean; path: string; error?: string } {
  try {
    // Ensure directory exists
    fs.mkdirSync(USER_SKILLS_PATH, { recursive: true });
    
    const skillDir = path.join(USER_SKILLS_PATH, skill.name);
    fs.mkdirSync(skillDir, { recursive: true });
    
    const skillPath = path.join(skillDir, "SKILL.md");
    const manifestPath = path.join(skillDir, "manifest.json");
    
    // Write SKILL.md
    const skillContent = `---
name: ${skill.name}
description: ${skill.description}
version: 1.0.0
author: mosaic-bot-auto
date: ${new Date().toISOString().split('T')[0]}
tags: [${skill.category}, auto-generated]
trigger_phrases:
${skill.triggers.map(t => `  - "${t}"`).join('\n')}
---

${skill.content}
`;
    
    fs.writeFileSync(skillPath, skillContent);
    
    // Write manifest
    const manifest = {
      name: skill.name,
      version: "1.0.0",
      createdAt: Date.now(),
      category: skill.category,
      autoGenerated: true,
      verified: true
    };
    fs.writeFileSync(manifestPath, JSON.stringify(manifest, null, 2));
    
    console.log(`[SkillForge] ✅ ACTUALLY CREATED: ${skill.name} at ${skillPath}`);
    
    return { success: true, path: skillPath };
  } catch (e) {
    console.error(`[SkillForge] ❌ FAILED to create ${skill.name}:`, e);
    return { success: false, path: "", error: String(e) };
  }
}

// Create skills based on ACTUAL detected needs (not hallucinated)
export const SKILL_TEMPLATES: Record<string, SkillTemplate> = {
  "dynamic-ip-handler": {
    name: "dynamic-ip-handler",
    description: "Handle HyperAIBox IP changes after reboot (C-3PO, R2-D2)",
    category: "infra",
    triggers: ["c3po unreachable", "ip changed", "box offline after reboot", "dynamic ip"],
    content: `# Dynamic IP Handler

## Problem
C-3PO and R2-D2 get new IPs from DHCP after reboot.

## Detection
1. Check last known IP (ping)
2. If unreachable, scan .100-.160 range
3. Update registry

## Commands
\`\`\`bash
# Scan for C-3PO
for ip in 192.168.0.{100..160}; do
  timeout 1 bash -c "echo >/dev/tcp/$ip/22" 2>/dev/null && echo "Found: $ip"
done

# Update registry
echo '{"c3po": "NEW_IP"}' > ~/.config/mosaic-companion/stargate-registry.json
\`\`\`
`
  },
  
  "health-endpoint-troubleshooter": {
    name: "health-endpoint-troubleshooter",
    description: "Debug health endpoint 404 errors (SPO, C-3PO, R2-D2)",
    category: "infra",
    triggers: ["health 404", "endpoint not found", "spo down", "fleet down"],
    content: `# Health Endpoint Troubleshooter

## Problem
Services return 404 on /health but are actually healthy.

## Reality
- SPO: :9100/ (any response = healthy)
- C-3PO: :9000/ (any response = healthy)  
- R2-D2: :9001/ (any response = healthy)

## Solution
Check ANY response, not just 200.

## Verification
\`\`\`bash
curl -s -o /dev/null -w "%{http_code}" http://192.168.0.112:9100/
# Returns 404 but service is HEALTHY
\`\`\`
`
  },
  
  "evolution-accelerator": {
    name: "evolution-accelerator",
    description: "Speed up Mosaic Bot self-improvement and skill creation",
    category: "agentic",
    triggers: ["evolve", "create skill", "improve bot", "self improvement", "new capability"],
    content: `# Evolution Accelerator

## How to Actually Create Skills (No Hallucination)

### Step 1: Verify Need
- Has this problem occurred 3+ times?
- Is there no existing skill?
- Will it benefit future operations?

### Step 2: Write to Filesystem
1. Create directory: ~/.config/mosaic-companion/mosaicbot/skills/mosaicbot-authored/NAME/
2. Write SKILL.md with frontmatter + content
3. Write manifest.json
4. VERIFY file exists before claiming success

### Step 3: Integration
- Skill appears in bundled-skills after next import cycle
- Available immediately in user-authored

### Step 4: Verification
Run: python3 ~/mosaic-evolution.py status
Should show: "skills_implemented: +1"

## Anti-Hallucination Rules
1. NEVER claim "created" without fs verification
2. ALWAYS report actual line counts from disk
3. If unsure: "Attempting to create..." not "Created 6 skills"
`
  }
};

// Export for heartbeat tools
export function getAvailableTemplates(): string[] {
  return Object.keys(SKILL_TEMPLATES);
}

export function createSkillFromTemplate(templateKey: string): { success: boolean; path?: string; error?: string } {
  const template = SKILL_TEMPLATES[templateKey];
  if (!template) {
    return { success: false, error: `Template "${templateKey}" not found` };
  }
  
  const result = forgeSkill(template);
  return result;
}
